### ISSUE TITLE
Suggestion.

### ISSUE THREAD

**Issue by polaris322** [barunkumar2696/competitive-coding#1]
Hi
I have suggestion. I'd like to chat with you via skype.
It is much more conveient to chat for me.
This is my skype.
live:.cid.efcaf344e756c808

PS: do not mention about skype in freelancer chatbox.
	It is breaching the terms and agreement. just say Yes or No

Thanks.

**Comment by barunkumar2696** [comment]
yes,but i dont have skype account.can u suggest any other source?

**Comment by barunkumar2696** [comment]
i am comfortable with facebok or linkdin

**Comment by polaris322** [comment]
could you create your skype account now?

**Comment by polaris322** [comment]
I can only chat freelancer or skype.

**Comment by barunkumar2696** [comment]
yes sure but my network is slow.i can do it in morning or just share ur email

**Comment by polaris322** [comment]
okay, I will wait.

**Comment by barunkumar2696** [comment]
can u use zoom?

**Comment by barunkumar2696** [comment]
account created

**Comment by polaris322** [comment]
I have only skype account, please create your skype account.
